name: grab_card_twitter
pack: robotpack
description: Grab card on twitter
enabled: true

trigger:
    type: twitter.stream_matched_tweet

criteria:
    trigger.text:
        type: "matchregex"
        pattern : "^(?=.*(?i)prize)(?=.*(?i)Stack_Storm)(?=.*(?i)robot)(?=.*(?i)OpenStackSummit).*$"

action:
    ref: robotpack.grab-card
    parameters: {}
